// node ops/hermes/radar-prompt.test.mjs — guardas del prompt del Prospect Radar v2 (que siga siendo seguro, acotado y pase por el Gateway)
import fs from 'node:fs';
let pass = 0, fail = 0;
const t = (n, c, x = '') => { c ? pass++ : fail++; console.log(c ? 'ok  ' : 'FAIL', n, c ? '' : x); };
const p = fs.readFileSync(new URL('./prospect-radar-v2.prompt.txt', import.meta.url), 'utf8');
t('modo explícito en la primera línea (MODO=auto | import | analyze)', /^MODO=(auto|import|analyze)\s*$/m.test(p.split('\n')[0]) && /MODO=analyze/.test(p));
t('obedece la compuerta de Atacama OS (skip → [SILENT]) y trabaja en modo seguro', /COMPUERTA DEL RADAR/.test(p) && /mode=skip/.test(p) && /\[SILENT\]/.test(p) && /MODO SEGURO/.test(p) && /max_imports/.test(p));
t('reporta cada corrida a atacama-ops (radar_report) sin imprimir la clave', /"action":"radar_report"/.test(p) && /atacama-ops/.test(p));
t('presupuesto acotado: ≤ 6 candidatos, ≤ 16 búsquedas, ≤ 30 llamadas, ≤ 12 minutos, ≤ 2 páginas por empresa', /máximo 6 candidatos/.test(p) && /máximo 16 búsquedas/.test(p) && /máximo 30 llamadas/.test(p) && /12 minutos/.test(p) && /Máximo 2 páginas/.test(p));
t('import limitado a 5 por corrida y solo los que el Gateway marcó create_in_ghl', /máximo 5 por corrida/.test(p) && /create_in_ghl/.test(p));
t('la única puerta es el Prospect Gateway (analyze → import con request_id fijo); no usa el ingest viejo ni escribe en GHL/Supabase', /atacama-prospect-gateway/.test(p) && !/-X POST "\$ATACAMA_INGEST_URL"/.test(p) && /no modifiques GHL ni Supabase directamente/.test(p) && /"request_id":"radar2-/.test(p));
t('nunca contacta a nadie ni envía mensajes', /no contactes ni escribas a nadie/.test(p) && /NO se envía/.test(p));
t('distingue HECHO / INFERENCIA / HIPÓTESIS y exige cita literal con URL', /HECHO/.test(p) && /INFERENCIA/.test(p) && /HIPÓTESIS COMERCIAL/.test(p) && /COPIADA LITERALMENTE/.test(p));
t('investigación intermedia: no exige «dolor demostrado», pero exige proceso observable y 2 hechos (regla de señal verdadera)', /no buscamos «dolor demostrado»/.test(p) && /SEÑAL VERDADERA vs RELLENO/.test(p) && /DOS hechos observados/.test(p) && /PROCESO observable/.test(p));
t('contacto solo público y de la propia empresa; sin adivinar correos; sin contacto público se descarta', /PÚBLICA publicada por la propia empresa/.test(p) && /Nunca adivines correos/.test(p) && /descarta la empresa/.test(p));
t('sin secretos incrustados en el prompt', !/(pit-[0-9a-f]{8}|eyJ[A-Za-z0-9_-]{20}|sk-[A-Za-z0-9]{20}|Bearer [A-Za-z0-9]{20})/.test(p));
const c = fs.readFileSync(new URL('./content-radar.prompt.txt', import.meta.url), 'utf8');
t('ambos radares terminan en [SILENT]: el aviso a Telegram lo arma Atacama OS, no el agente', /EXACTAMENTE «\[SILENT\]»/.test(p) && /EXACTAMENTE «\[SILENT\]»/.test(c) && /content_radar_report/.test(c) && !/Responde SOLO con un resumen/i.test(p + c));
// ---- Ola A: prompts de los jobs de contenido (RSS, piezas, inteligencia orgánica)
const rss = fs.readFileSync(new URL('./content-rss.prompt.txt', import.meta.url), 'utf8');
const pcs = fs.readFileSync(new URL('./content-pieces.prompt.txt', import.meta.url), 'utf8');
const cmp = fs.readFileSync(new URL('./content-competitors.prompt.txt', import.meta.url), 'utf8');
const all = [['rss', rss], ['pieces', pcs], ['competitors', cmp]];
t('Ola A: los tres prompts obedecen la compuerta (skip → [SILENT]) y terminan en [SILENT]', all.every(([, x]) => /COMPUERTA/.test(x) && /mode=skip/.test(x) && /exactamente «\[SILENT\]»/i.test(x)));
t('Ola A: los tres registran la corrida con report_content_job y su tipo', /kind="content_rss"/.test(rss) && /kind="content_pieces"/.test(pcs) && /kind="competitor_intel"/.test(cmp) && all.every(([, x]) => /report_content_job/.test(x)));
t('Ola A: ninguno publica, programa ni contacta, y ninguno trae claves', all.every(([, x]) => /no publicas|Nada se publica|no contactes|no contactas/i.test(x)) && all.every(([, x]) => !/(pit-[0-9a-f]{8}|eyJ[A-Za-z0-9_-]{20}|sk-[A-Za-z0-9]{20}|Bearer [A-Za-z0-9]{20})/.test(x)));
t('Ola A: RSS exige abrir la URL y cita LITERAL, marcar todos los revisados y no redactar piezas', /LITERALMENTE/.test(rss) && /rss_items\(action="mark"/.test(rss) && /NO redactes la pieza/.test(rss));
t('Ola A: piezas autónomas solo linkedin_page (linkedin_profile es de Christian), origin autonomous, sin comment_keyword', /linkedin_profile está PROHIBIDO/.test(pcs) && /origin="autonomous"/.test(pcs) && /NUNCA inventes un recurso ni uses comment_keyword/.test(pcs) && /schedule_suggestion: null/.test(pcs));
t('Ola A: piezas reutilizan recursos existentes y respetan la cola', /content_resources\(action="list"/.test(pcs) && /pieces_allowed/.test(pcs) && /blocked \(cola llena: detente/.test(pcs));
t('Ola A: inteligencia orgánica es solo fuentes públicas, no copia, páginas leídas reales y no es Ads Radar', /PÚBLICAS/.test(cmp) && /sin iniciar sesión/.test(cmp) && /NO es copiar/.test(cmp) && /NO es el radar de anuncios pagados/.test(cmp) && /SOLO las URLs que abriste/.test(cmp) && /nunca adivines un sitio|no adivines|Nunca adivines|no lo encuentras con certeza/i.test(cmp));
console.log(`\n${pass} ok ${fail} fallos`);
process.exit(fail ? 1 : 0);
